### ISSUE TITLE
Im horrible at coding and i cant get the layout to work

### ISSUE THREAD

**Issue by EloEelis** [uofuv/flipper-zero-badusb-swedish-finnish-keyboard-layout#1]
So basically all i have done is extracted the folder and put the file in my flipper zero layout folder and as epected it doesent work or show up.

**Comment by uofuv** [comment]
@EloEelis Yeah, seems they changed the structure a bit since I made this. Updated a bit. The below should work. I also uploaded an already compiled .dfu to the repo that you could just download and flash, https://github.com/uofuv/flipper-zero-badusb-swedish-finnish-keyboard-layout/blob/main/flipper-z-0.100.3-swedish-finnish-badusb.dfu

`git clone https://github.com/uofuv/flipper-zero-badusb-swedish-finnish-keyboard-layout.git`
`git clone --recursive https://github.com/flipperdevices/flipperzero-firmware.git`
`cp flipper-zero-badusb-swedish-finnish-keyboard-layout/furi_hal_usb_hid.h flipperzero-firmware/targets/furi_hal_include/furi_hal_usb_hid.h`
`cd flipperzero-firmware`
`./fbt`
=> output is saved in `build/`
